### ISSUE TITLE
update email text/copy/style/sender

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#10]
1. Update sender

current sender is from Eric <eric@tenantreport.net>
Update to "Found Lost Item!!!"<found@lost-item.com">

2. Fix the "how" key (currently showing "undefined")
https://monosnap.com/file/9trXXxl2mQRCL6EaRT2B2sUBfa4XXK

3. Update copy

Great news, {firstname}!

Someone found something that belongs to you!

What did they find? **{what they found}**
Where did they find it? **{where}**
Here's how you can get it back:
**{how}**

Have a great day! :)

**Comment by aldarund** [comment]
2, 3 done
1 - you need to verify found@lost-item.com in postmark https://account.postmarkapp.com/signature_domains

**Comment by ezl** [comment]
@aldarund i verified it by clicking on the link in the email sent to me by postmark.

however, the postmark page still says "DKIM Not VerifiedReturn-Path Not Verified".

I've forwarded you the email I received and clicked.

Please let me know if I need to do anything further.

**Comment by aldarund** [comment]
@ezl It should be done in domain dns
https://account.postmarkapp.com/signature_domains/1312945

**Comment by ezl** [comment]
https://monosnap.com/file/nTFZMeGWMWh8bdc5sLMXCZ9dYi5W41

@aldarund lmk if anything further is needed from me in order to be able to start sending from lost-item.com accounts
