### ISSUE TITLE
look into firebase error

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#32]
> There was an error while sending the email: { ApiInputError: You tried to send to a recipient that has been marked as inactive.
> Found inactive addresses: hgjghjgh@asda.dru.
> Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression. 

What's up with this weird fake email address? Seems to be triggered every time we send any emails.

**Comment by mascarell** [comment]
This happens when the user (in this case that weird email) marked lost-item emails as spam or blocked them.

> Seems to be triggered every time we send any emails.

Does it happen every time you send an email no matter to whom? Or just when you send an email related to their account?

**Comment by ezl** [comment]
@mascarell when i fill the form on lost-item.com/eric, it sends an email to my actual gmail, which is the correct behavior. I RECEIVE that email. Yet somehow firebase logs this error that we attempted to send to this invalid email address.

**Comment by mascarell** [comment]
Found nothing on the repositories for nodemailer-postmark-transpor and nodemailer.

Looking through postmark repositories and web results landed me on a couple explanations but nothing technical, do you want me to look further into this or focus on the redesign?

**Comment by ezl** [comment]
@mascarell you can ignore this now. I also grepped the repository and it doesn't make sense to me.

@aldarund can you take a look at this ticket?
