### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#34]
using the new design icon in files in 
https://www.notion.so/ezl/Redesign-Assets-2f47c78742bd4834b539fef07e423f4e

**Comment by mascarell** [comment]
Love the new design!

I'm on windows, could I get some .psd or affinity designer files? It's mostly for the logo, the web I can work with the exported files and the invision screens for now!

**Comment by ezl** [comment]
hmmm -- i can find a way to export the logo.

there is not a PSD of this, and we won't port it. best thing to do is reproduce it with as high fidelity as you can by just taking screenshots, then ask me for the specific images and I'll export them to the size you ask for

**Comment by mascarell** [comment]
I do have a macbook, I just don't use it that often, I'll get sketch there so we can work faster!

**Comment by ezl** [comment]
lovely. :)

**Comment by ezl** [comment]
@mascarell I see this is complete -- closing this ticket.
