### ISSUE TITLE
Question: Should we remove "Store" menu item?

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#50]
@mascarell I see there's a "store" link in the menu:
https://monosnap.com/file/5pE3wm8r7EhuZeq0JRaQj6favTGK8x

However, I didn't see that in the notion design:
https://www.notion.so/ezl/Web-3e0ae18e13834e0abb721776b0fca0ef

(just has dashboard/how it works when logged in)

Is "Store" a legacy link from the previous design?

**Comment by mascarell** [comment]
I got that from the files on notion in sketch, wasn't sure as to include it or not, we can remove it for now if you're not planning on making the store page (yet / short term)
