### ISSUE TITLE
Make hamburger menu lines equal length

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#51]
These lines for the hamburger menu aren't equal length:
https://monosnap.com/file/f5MSCyRtymWJkZDVlIfO2NSd55USCP

(A) is that intentional?
(B) is it rendering different for you?

If this is NOT intentional and you can replicate this bug, please make the lines equal in length.

**Comment by mascarell** [comment]
It was intentional-ish, copied the CSS for the animation from my latest project (a game website) and had that style, it didn't look bad so I left it, but should've asked first, I'll make them same length, no problem 😄
