### ISSUE TITLE
redirect http -> https

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#8]

**Comment by aldarund** [comment]
@ezl its something you should do https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site

**Comment by ezl** [comment]
@aldarund are you able to do this? if not, is this due to the fact this is a personal repository rather than company? if so, maybe we should migrate back. i'd prefer not to be a bottleneck for this project.

**Comment by aldarund** [comment]
@ezl no, im not able to do this. And this repo wasnt in org , it was always in your account :)

**Comment by ezl** [comment]
@aldarund -- you're right. it was super easy. I should have done it before but I was worried it was going to be a lot of work. :P solved now.
