### ISSUE TITLE
lost item form page updates

### ISSUE THREAD

**Issue by ezl** [ezl/lost-item#9]
https://monosnap.com/file/kq40J8d5CIlJrRpsEHQZsQrewTDvOr

example: https://www.lost-item.com/7g4pxn

Note, replacing the send button with -> "sending" state -> then "success" text (no button) will prevent the button from being pressed multiple times (currently we allow that)

**Comment by aldarund** [comment]
returned not logged to dom.. Its a word from last sentence
https://i.imgur.com/rDvvMYk.png
